# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Christopher MANEU
email: hello@maneu.net
description: >
  Codelicious
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.maneu.net" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Christopher MANEU'
bio: >
  Engineer @Microsoft ğŸ“± / â˜ï¸ | Previously @Deezer & Microsoft #MVP | Scuba diving instructor ğŸ 
author_image: "/assets/images/author.jpg"
twitter_username: cmaneu
github_username:  cmaneu

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
